hkml: print help info instead of exception when no args given
If you run hkml with no args given, it print a exception error:

./hkml
Traceback (most recent call last):
  File "/Volumes/Codebase/projects/hackermail/./hkml", line 32, in <module>
    if len(sys.argv) > 0 and sys.argv[1] == '--cli_complete':
                             ~~~~~~~~^^^
IndexError: list index out of range

Fix that by print the usage info instead.

Signed-off-by: Kairui Song <kasong@tencent.com>